### ISSUE TITLE
Deprecate this cookbook

### ISSUE THREAD

**Issue by martinb3** [the-galley/rackspace_support#10]
We agreed to use templates with libraries for customer cookbooks; therefore, this cookbook should be deprecated.

**Comment by TheSeubert** [comment]
This cookbook externalizes Rackspace specific configurations that we:
- May need to change or manage differently in the future
- Manage in an effort to not clutter the customer cookbooks
- Provide a centralized place for Rackspace specifics

By deprecating this cookbook into the base templates, you clutter the customer cookbook and make it extremely hard to update and manage these pieces in those cookbooks.

Not everything has to be a template or library, and this cookbook can be updated itself to use libraries where necessary.

I can agree to move the firewall piece into the templates, as this does make sense.

**Comment by twistedgrim** [comment]
From the support side a cleaner cookbook on the customer's cookbook makes it easier on all of the support rackers managing it. This also streamlines any customers onboarding/offboarding and any customers who do not want full managed devops support, but still want assistance at times. Having this in one place as Justin says allows us to add features and changes to all customers easily. Breaking what platformstack does down into simple pieces is really what makes having and managing our own cookbooks valuable. Doing that for every customer does not add value and expand the reach of what we can do easily.

++ Firewall But Racker access and standard packages makes sense to me.

**Comment by martinb3** [comment]
This cookbook: 
- was designed and written without review from the group
- has not had any peer review (22 commits to master and only 6 pull requests)
- has no CI testing
- is un-evenly distributed across implementations (some use, some don't)
- duplicates things we have been maintaining in other places

> Breaking what platformstack does down into simple pieces is really what makes having and managing our own cookbooks valuable

This is exactly why we wrote libraries for each component. Putting them back in a mini-platformstack like this cookbook feels like a step backwards.

**Comment by TheSeubert** [comment]
Thanks for your comments Martin, we can discuss this in our group chats.

**Comment by dearing** [comment]
I don't think so.  
- It serves a purpose for now.  
- Clean, simple.  
- Sure it needs testing; simple afternoon of work.
- Libraries are cool, and obliterate the depends problem.

**Comment by martinb3** [comment]
We discussed this in a tech forum, and we think we should have the maintainers get together and discuss how to reduce duplication of effort (vs. duplication of cookbooks).

**Comment by jujugrrr** [comment]
I do agree with @martinb3. We have to prevent duplication. 
Part of this has already been done in libraries. We are working on finding the best solution to each problem. If we join effort rather than duplicating work we will be able to deliver(good code, good test, good doc, good communication, good design) faster the libraries/cookbooks we need.

> It serves a purpose for now.

We have to be careful not having to many of this cookbook/repository which were supposed to help for now and ended up being used as a standard without the quality required on a standard.

> Clean, simple.

It looks like a small platformstack, the scope is not clear and it might end up being a lot more complex.

> Sure it needs testing; simple afternoon of work.

I think it **should not be used on production** without testing. Part of the standard we implement on each library is to have a complete documentation and test coverage.
