### ISSUE TITLE
Merge rackspace_support to platformstack

### ISSUE THREAD

**Issue by marcoamorales** [the-galley/rackspace_support#3]
While reviewing this cookbook, I have found very few differences between `rackspace_support` and `platformstack`. Mainly the only difference I could find is that `rackspace_support` includes two common packages not included in `platformstack`.

```
tmux
git
```

**Comment by TheSeubert** [comment]
The reason this cookbook was created was because of too many dependencies in platformstack. This was meant to be a very lean (KISS) only what is necessary cookbook.

I don't know of a better way to fix platformstack, other than not to maybe, since it is technically a stack piece. Open for discussion on the matter of course :)

**Comment by marcoamorales** [comment]
If you drive for a living, would you want to reinvent the wheel every time you get a flat tire?

A _better_ way to fix platformstack is to review its recipes and purge any unneeded dependencies.

**Comment by TheSeubert** [comment]
No, but depending on how damaged my tire is, I would need a whole new and maybe newly designed tire that works. You can only patch that poor flat tire so much before it's a rat nest of fixes :)

I agree and see your point, but I disagree in how to approach I suppose.

**Comment by brint** [comment]
Lets move this into conversation.

**Comment by jarosser06** [comment]
Agree with @brint closing this issue.
